#
# Erstellt eine Control Plane Node fuer Platen Kurs
#

vm:
  count: 1
  cpu: 4
  memory: 12Gi
  storage: 64Gi  
  userdata: https://raw.githubusercontent.com/mc-b/platen/refs/heads/v2/cloud-init-control.yaml
  ports:
    - 16443
    - 18888
    - 30443